env:
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ["tsconfig.json"]
rules: {
  "@typescript-eslint/quotes": ["error","double"],
  "@typescript-eslint/strict-boolean-expressions": 0,
  "@typescript-eslint/prefer-nullish-coalescing": 0,
  "@typescript-eslint/semi": ["error", "always"],
  "@typescript-eslint/no-misused-promises": [
    "error",
    {
      "checksVoidReturn": false
    }
  ]
}
