services:
  app:
    build: .
    environment:
      PORT: 3001
      MONGO_USER: ${MONGO_USER}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: 27017
      MONGO_HOST: ${MONGO_HOST}
    ports:
      - "3001:3001"
    expose:
      - 3001
    depends_on:
      - db
  db:
    image: "mongo:latest"
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./pixar/movies.json:/tmp/movies.json:ro
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - db_data:/data/db
volumes:
  db_data: